export const FETCH_CHARACTERS = 'CHARACTERS/FETCH_CHARACTERS';
export const FETCH_CHARACTERS_SUCCESS = 'CHARACTERS/FETCH_CHARACTERS_SUCCESS';
export const FETCH_CHARACTERS_ERROR = 'CHARACTERS/FETCH_CHARACTERS_ERROR';

export const FETCH_EPISODES_BY_CHARACTER = 'CHARACTERS/FETCH_EPISODES_BY_CHARACTER';
export const FETCH_EPISODES_BY_CHARACTER_SUCCESS = 'CHARACTERS/FETCH_EPISODES_BY_CHARACTER_SUCCESS';
export const FETCH_EPISODES_BY_CHARACTER_ERROR = 'CHARACTERS/FETCH_EPISODES_BY_CHARACTER_ERROR';
